# Generated by Django 4.2.9 on 2024-10-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
